### ISSUE TITLE
cannot open the portal after fresh install

### ISSUE THREAD

**Issue by ytwytw** [jprochazka/adsb-receiver#145]
I cannot open the portal after clean install on a rpi2

i didnt enable advance feature for the portal

log here

```
2016-04-10 20:12:48: (mod_fastcgi.c.2695) FastCGI-stderr:   thrown in /var/www/html/classes/common.class.php on line 56
2016-04-10 20:12:48: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /var/www/html/classes/common.class.php:56
2016-04-10 20:12:48: (mod_fastcgi.c.2695) FastCGI-stderr: Stack trace:
2016-04-10 20:12:48: (mod_fastcgi.c.2695) FastCGI-stderr: #0 /var/www/html/classes/common.class.php(56): PDO->__construct('mysql:host=loca...', 'adsbuser', 'password')
2016-04-10 20:12:48: (mod_fastcgi.c.2695) FastCGI-stderr: #1 /var/www/html/classes/common.class.php(82): common->pdoOpen()
2016-04-10 20:12:48: (mod_fastcgi.c.2695) FastCGI-stderr: #2 /var/www/html/classes/template.class.php(68): common->getSetting('template')
2016-04-10 20:12:48: (mod_fastcgi.c.2695) FastCGI-stderr: #3 /var/www/html/classes/template.class.php(42): template->readTemplate('master.tpl')
2016-04-10 20:12:48: (mod_fastcgi.c.2695) FastCGI-stderr: #4 /var/www/html/dump1090.php(46): template->display(Array)
2016-04-10 20:12:48: (mod_fastcgi.c.2695) FastCGI-stderr: #5 {main}
2016-04-10 20:12:48: (mod_fastcgi.c.2695) FastCGI-stderr:   thrown in /var/www/html/classes/common.class.php on line 56
```

**Comment by jprochazka** [comment]
Looks as though you ran the portal install page and set things up to use MySQL. Rerun http://[YOUR_IP_ADDRESSS]/admin/install.php and select XML as where data should be stored.

**Comment by ytwytw** [comment]
@jprochazka it works

Thanks

Maybe need to add those into readme.md so other people would know

Thanks,
