### ISSUE TITLE
Upgrade to 2.0.1 broke entire install

### ISSUE THREAD

**Issue by stevepmitchell** [jprochazka/adsb-receiver#185]
Upgraded to v2.0.1 on two different systems, and now have errors about tables in the lighttpd logs.  Can't complete the install PHP script:

2016-05-07 22:58:30: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: settings' in /var/www/html/classes/common.class.php:88
2016-05-07 22:58:30: (mod_fastcgi.c.2695) FastCGI-stderr: Stack trace:
2016-05-07 22:58:30: (mod_fastcgi.c.2695) FastCGI-stderr: #0 /var/www/html/classes/common.class.php(88): PDO->prepare('SELECT * FROM s...')
2016-05-07 22:58:30: (mod_fastcgi.c.2695) FastCGI-stderr: #1 /var/www/html/index.php(39): common->getSetting('defaultPage')
2016-05-07 22:58:30: (mod_fastcgi.c.2695) FastCGI-stderr: #2 {main}
2016-05-07 22:58:30: (mod_fastcgi.c.2695) FastCGI-stderr:   thrown in /var/www/html/classes/common.class.php on line 88
2016-05-07 22:58:45: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: settings' in /var/www/html/classes/common.class.php:88

**Comment by stevepmitchell** [comment]
I can't get into the admin tools to fix the SQL settings or even finish the process at the end of the upgrade.  I'm not sure if I can disable SQLite logging and get by this error, or how I can get the web UI to work again.  

I'm not 100% sure the actual clients are working, although some have started, and dump1090 appears to be running too...

**Comment by radiostationx** [comment]
I had the same issue, and followed Joes advice in this thread

http://discussions.flightaware.com/ads-b-flight-tracking-f21/ads-b-receiver-project-setup-scripts-t36532-1050.html

"If you run into a problem during the PHP installation portion where you are forwarded to the page /install/upgrade.php after submitting the form found at /install/ delete the file /var/www/html/classes/settings.class.php and visit the /install/ URL once more."

This worked fine on my 2.0.1 install.

**Comment by jprochazka** [comment]
This POST problem is becoming really annoying... I just committed a change to how the code checks if the data has been posted. It has been hard to recreate the issue even though I know it is there. I can only recreate it sporadically which has made tracking down the issue quite hard.

Let me know if the link @radiostationx posted does not help.

**Comment by stevepmitchell** [comment]
I was able to get up and running with the tips left by @radiostationx

**Comment by jprochazka** [comment]
Glad to hear. Still banging my head up against the wall trying to figure out why this is happening in particular on Raspbian. Going to close this issue being it is mensioned elsewhere and you have since got things resolved on your end.
