### ISSUE TITLE
column not being created by setup in flightNotifications db

### ISSUE THREAD

**Issue by target-drone** [jprochazka/adsb-receiver#327]
error at /var/www/html/api/notifications.php:66, `"SELECT flight, lastMessageCount FROM ".$settings::db_prefix."flightNotifications";` gives lots of this in the webserver error log

```
2017-03-14 05:48:32: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such column: lastMessageCount' in /var/www/html/api/notifications.php:66
2017-03-14 05:48:32: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2017-03-14 05:48:32: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/html/api/notifications.php(66): PDO->prepare('SELECT flight, ...')
2017-03-14 05:48:32: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /var/www/html/api/notifications.php(36): getVisibleFlights()
2017-03-14 05:48:32: (mod_fastcgi.c.2543) FastCGI-stderr: #2 {main}
2017-03-14 05:48:32: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/html/api/notifications.php on line 66
```
Which looks to be correct as there are only two columns being created by the setup script, adsb-receiver/build/portal/html/install/index.php
```
$flightNotificationsSql = 'CREATE TABLE '.$dbPrefix.'flightNotifications (
   id INT(11) PRIMARY KEY AUTO_INCREMENT,
   flight VARCHAR(10) NOT NULL);';
```

**Comment by jprochazka** [comment]
Honestly I have been gone awhile and there is a fork of a branch which contained unfinished/untested code added to a development branch. If possible could you supply the version you are running? If not I will take it that this issue pertains to the forked development branch and close it in the near future.

**Comment by jprochazka** [comment]
Removed the column `lastMessageCount` that was to be used for a feature that was to be added in the previous planned v2.7.0 release that somehow found its way into the master aka v2.6.0 branch.
