### ISSUE TITLE
Can't compile Piaware

### ISSUE THREAD

**Issue by youknow10** [jprochazka/adsb-receiver#435]
Here's the error I get:

```
cc -g -o faup1090 faup1090.o anet.o mode_ac.o mode_s.o net_io.o crc.o stats.o cpr.o icao_filter.o track.o util.o -Wl,-Bsymbolic-functions -Wl,-z,relro -lpthread -lm -lrt
make[2]: Leaving directory '/home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie/dump1090'
pyvenv /home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie/debian/venv --without-pip
WARNING: the pyenv script is deprecated in favour of `python3.6 -m venv`
cd cx_Freeze-4.3.4 && /home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie/debian/venv/bin/python ./setup.py install
Traceback (most recent call last):
  File "./setup.py", line 138, in <module>
    finder = cx_Freeze.ModuleFinder(bootstrap = True)
  File "/home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 160, in __init__
    self._AddBaseModules()
  File "/home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 187, in _AddBaseModules
    self.IncludeModule("traceback")
  File "/home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 687, in IncludeModule
    namespace = namespace)
  File "/home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 355, in _ImportModule
    deferredImports, namespace = namespace)
  File "/home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 445, in _InternalImportModule
    parentModule, namespace)
  File "/home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 511, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "/home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 597, in _ScanCode
    arguments.append(co.co_consts[opArg])
IndexError: tuple index out of range
debian/rules:55: recipe for target 'build_cxfreeze' failed
make[1]: *** [build_cxfreeze] Error 1
make[1]: Leaving directory '/home/myuser/Downloads/piaware_builder/adsb-receiver/build/piaware_builder/package-jessie'
debian/rules:83: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

```

This is my system:
Linux MyComp 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I already have dump1090 working and feeding to FlightRadar24 and Planefiner. I just want to feed to FlightAware too.

**Comment by jprochazka** [comment]
I am not familiar with Linux MyComp but looking at the error you posted it looks much like the error I ran into with Ubuntu since Ubuntu 17.10. This is actually an issue more suited for the developer(s) piaware_builder. If you were to post this issue they I am sure they would be able to help out.

https://github.com/flightaware/piaware_builder/issues/10

Here is a link to the similar issue I posted to the PiAware repository instead of piaware_builders mistakenly. https://github.com/flightaware/piaware/issues/41
