### ISSUE TITLE
"PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: name in "

### ISSUE THREAD

**Issue by Conan179** [jprochazka/adsb-receiver#437]
i want use a sqlite database for advance option.
After install, the web portal donst running:
Raspberry pi
/var/log/lighttpd/error.log
2018-06-10 00:06:25: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 near ",": syntax error in /var/www/html/install/index.php:359
2018-06-10 00:06:25: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2018-06-10 00:06:25: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/html/install/index.php(359): PDO->prepare('CREATE TABLE ad...')
2018-06-10 00:06:25: (mod_fastcgi.c.2543) FastCGI-stderr: #1 {main}
2018-06-10 00:06:25: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/html/install/index.php on line 359
2018-06-10 00:14:37: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: adsb_settings in /var/www/html/classes/common.class.php:95
2018-06-10 00:14:37: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2018-06-10 00:14:37: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/html/classes/common.class.php(95): PDO->prepare('SELECT * FROM a...')
2018-06-10 00:14:37: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /var/www/html/install/index.php(39): common->getSetting('version')
2018-06-10 00:14:37: (mod_fastcgi.c.2543) FastCGI-stderr: #2 {main}
2018-06-10 00:14:37: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/html/classes/common.class.php on line 95

**Comment by jprochazka** [comment]
@vitaliy-sk commited a fix which has been merged into the master branch today which addresses SQLite installations. https://github.com/jprochazka/adsb-receiver/pull/422
